### PR TITLE
Allow Symfony 4

### PR DESCRIPTION
**Pull request by sminnee**
Note that this will need to be rebased after my PR #9 has been merged.

### CODE REVIEW

**Comment by sminnee** [comment]
Rebasing this now

**Comment by sminnee** [comment]
@unclecheese waddaya reckon?

**Comment by unclecheese** [comment]
LGTM

**Comment by unclecheese** [comment]
Tagged 0.1.0 cause feels like it's time.

**Comment by sminnee** [comment]
0.1.0 is usually my 2nd comment 😆

**Pull request merged**
